### Locations frontend API configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.2

logging:
  level: INFO
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/locations-frontend.log
      archivedLogFilenamePattern: logs/locations-frontend-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

locations:
  esUrl: http://elastic-search-url.example.com:9300
  esIndex: elastic-search-index
  estype: elastic-search-type
  esIndexService: elastic-search-services-index
  estypeService: elastic-search-services-type
  searchDistance: "1km"

api:
  endpointUri: https://api.oregonstate.edu/v1/
